### ISSUE TITLE
Mittige Schrift + Umrandung bei allen Punkten

### ISSUE THREAD

**Issue by LxWiebe** [axeff/animalfarm#12]
Kann man alle Texte mittig setzen und jeden Navigationspunkt weiß umranden? 
Kommt uneinheitlich, wenn man umrandet sind und manche nicht...

![image](https://cloud.githubusercontent.com/assets/26739119/24554235/1bf79fa8-162d-11e7-811c-69abd70f3261.png)

**Comment by axeff** [comment]
@ruskykrass Weiß grad nicht genau was du mit umranden meinst. Und soll die Auflistung in die Mitte rutschen, aber linksbündig bleiben, oder den Text zentrieren?
