### ISSUE TITLE
Navigationspunkt Tickets

### ISSUE THREAD

**Issue by LxWiebe** [axeff/animalfarm#14]
LIMITED SECOND MOUSE TICKETS - Bitte in TICKETS umbennen.

Und vorher hatten wir doch zumindest eine große Grafik auf die Tickets. Jetzt ist es wenig aufmerksamkeitserregend.

**Comment by axeff** [comment]
@ruskykrass Grafik war da noch nicht. Kann aber gerne was einbauen. Rasmus wollte nen Button basteln...
