### ISSUE TITLE
Naivigationspunkte vertauschen

### ISSUE THREAD

**Issue by LxWiebe** [axeff/animalfarm#16]
Kann man Programm über die Infos setzen. Das gehört thematisch noch zu LineUp. So haben wir die beiden Sachen beieinander. 

![image](https://cloud.githubusercontent.com/assets/26739119/24554624/8fa4266e-162e-11e7-9b24-7c663cd63035.png)

**Comment by axeff** [comment]
Ja klar, ich hatte die eigenmächtig getauscht aus rein subjektiven Gründen. Weil man sonst 2 gelb/lila-Verlaufsblöcke untereinander hat.
