### ISSUE TITLE
Impressum 

### ISSUE THREAD

**Issue by LxWiebe** [axeff/animalfarm#20]
Carl-Christian Bruns
Pflüger Str. 25
12407

Alexander Wiebe
Skalitzer Str. 105
10997 Berlin

**Comment by axeff** [comment]
@ruskykrass Any News?

**Comment by LxWiebe** [comment]
Yes - wir nehmen oben genannte Adressen als Impressum.

**Comment by axeff** [comment]
So in etwa?
![impressum](https://cloud.githubusercontent.com/assets/494596/25183254/5997998c-2517-11e7-9626-d91cbc255f6b.png)

**Comment by LxWiebe** [comment]
Kann man das auch in ein Pop-Up packen?
