### ISSUE TITLE
Beschreibung Dharma Yoga Workshop (ehemals Bondage Workshop) 

### ISSUE THREAD

**Issue by LxWiebe** [axeff/animalfarm#23]
Die erste Beschreibung für ein Workshop ist da. Das wird doch kein Bondage Workshop, sondern ein Dharma Yoga Workshop. Ich habe den Beschreibungstext unten eingefügt. Kann man die Namen der Workshops in dem selben Font, wie die Acts im LineUp machen? Das kommt etwas schicker.
So in etwa soll das dann aussehen:

Was wäre die Animal Farm ohne sinnstiftende und lehrreiche Workshops?
Dieses Jahr werden folgende Workshops angeboten:

**Love Salon (TBD.)**

**Kakao Zeremonie mit Contact Dance (TBD.)**

**Dharma Yoga Workshop**
“All is within.” Dharma Mittra

Wir – Nico, April, Mona, Hélène und Patricia – sind Teil des Teams im Dharma Yoga Studio Berlin, das vor über einem Jahr seine Türen in Berlin Neukölln geöffnet hat. Wir haben uns vorgenommen, Euch das Yoga-Universum ein wenig näher zu bringen, genauer Dharma Yoga, einen von unzähligen Stilen in Hatha Vinyasa, der seit fast 50 Jahren von Sri Dharma Mittra in New York gelehrt wird.

In unseren Klassen flowt ihr nach einer kurzen Meditation aus der Kobra in den herabschauenden Hund und verwandelt euch später vielleicht von einer Schildkröte in eine Taube oder ein Kamel – im Yoga sind die meisten Körperhaltungen nämlich nach Tieren benannt und wir basteln bereits Animal-Flows.  

Neben dieser klassischen Yoga-Art bringen wir Euch weitere Yogastile und –techniken, sowie Workshops mit zum Festival. Weitere Informationen findet ihr demnächst im Programm und wer jetzt schon Lust bekommen hat, vorab mal bei uns vorbei zu schauen, findet uns hier: Dharma Yoga Berlin (den Link hinterlegen https://www.dharmayogaberlin.com)

Bring your mat and see you there, und bis dahin

„Be receptive!“

**Comment by axeff** [comment]
Ne Idee wie das Aussehen soll?
![So sicherlich nicht...](https://cloud.githubusercontent.com/assets/494596/25182293/6f2fe31a-2514-11e7-92e4-5b5781df43b7.png)

**Comment by LxWiebe** [comment]
Kann man das so machen, dass man ein PopUp macht und hinter einem Link versteckt, den man farblich hervorhebt und unterstreicht? (Infos)
