### ISSUE TITLE
Farbverlauf bei den einzelnen Sections anpassen

### ISSUE THREAD

**Issue by LxWiebe** [axeff/animalfarm#30]
Bitte einmal den selben Farbverlauf bei allen Sections gleichmachen (den Farbverlauf der Ticket-Sektion nehmen.)

**Comment by axeff** [comment]
Sähe dann so aus:

[Screen.webm.zip](https://github.com/axeff/animalfarm/files/935178/Screen.webm.zip)

**Comment by LxWiebe** [comment]
Finde ich gut.
