### ISSUE TITLE
Telefonnummer in NL Anmelde Formular hinzufügen

### ISSUE THREAD

**Issue by LxWiebe** [axeff/animalfarm#31]
Können wir noch ein dritter Formularfeld mit der Telefonnummer einfügen?

**Comment by axeff** [comment]
@ruskykrass als Pflichtfeld?

**Comment by LxWiebe** [comment]
Nein! Um Gottes Willen :)

2017-05-13 21:39 GMT+02:00 Axel Freudiger <notifications@github.com>:
